### ISSUE TITLE
conflict with material dialog library

### ISSUE THREAD

**Issue by anantshah93** [lawloretienne/ImageGallery#10]
after using this library and material dialog library gradle will show **error** that drwable resource **not** **found** related to alpha_close.

**gradle** file
compile('com.github.afollestad.material-dialogs:core:0.8.5.1@aar') {
        transitive = true
    }
    compile 'com.github.lawloretienne:imagegallery:0.0.13'

**Error**:

/Users/apple/Desktop/androidApp/app/build/intermediates/exploded-aar/com.github.afollestad.material-dialogs/core/0.8.5.1/res/values-v11/values-v11.xml

Error:(3, 5) No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha').

**Comment by lawloretienne** [comment]
Checkout http://stackoverflow.com/questions/35632576/error-cannot-find-symbol-variable-abc-ic-ab-back-mtrl-am-alpha . I dont think this issue is with my library.

**Comment by anantshah93** [comment]
ok i will try thanks, but i posted here because of after declaring this lib to my project i m getting this error and if i remove this lib and again sync project , error was gone so i did anyway, thank you i will again try to integrate your library and you developed good library...
