### ISSUE TITLE
Unable load Image with Glide Library

### ISSUE THREAD

**Issue by ledangtuanbk** [lawloretienne/ImageGallery#14]
Hi Team. 
For some reason, I want to use **[Glide](https://github.com/bumptech/glide)**  library to load image instead of **Picasso** as your example. 
When I used Glide, The image not able to load Image. 

My code like that: 

`public void loadFullScreenImage(final ImageView iv, final String imageUrl, int width, final LinearLayout bgLinearLayout) {
            Log.d(TAG, "loadFullScreenImage: " + imageUrl);
            Glide.with(iv.getContext()).load(imageUrl).into(iv);
        } else {
            iv.setImageDrawable(null);
        }
    }
`
Please help me to do it. 
Thank you very much.

**Comment by sushant23** [comment]
+1

**Comment by davidpini** [comment]
+1

**Comment by Hitexroid** [comment]
+1

**Comment by lawloretienne** [comment]
So I just tried this for `Glide` integration and it works.

``` java
@Override
public void loadFullScreenImage(final ImageView iv, String imageUrl, int width, final LinearLayout bgLinearLayout) {
    if (!TextUtils.isEmpty(imageUrl)) {
        SimpleTarget target = new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(final Bitmap bitmap, GlideAnimation glideAnimation) {
                Palette.from(bitmap).generate(new Palette.PaletteAsyncListener() {
                    public void onGenerated(Palette palette) {
                        applyPalette(palette, bgLinearLayout);
                        iv.setImageBitmap(bitmap);
                    }
                });
            }
        };

        Glide.with(iv.getContext())
                .load(imageUrl)
                .asBitmap()
                .override(width, width)
                .into(target);
    } else {
        iv.setImageDrawable(null);
    }
}
```
