### ISSUE TITLE
Hide ToolBar

### ISSUE THREAD

**Issue by spaine** [lawloretienne/ImageGallery#16]
Would be nice to be able to hide the toolbar when in FullScreenImageGalleryActivity.

Single tap will hide the toolbar, tapping again would show it.

Will help on images where there are text at the upper part.

Thanks!

**Comment by lawloretienne** [comment]
Do you have an example image url that has this issue or could you post a screenshot of the issue. Also the image view in this library supports pinch to zoom. so it would be tricky to have that and immersive mode. I think you can only have one or the other.

**Comment by spaine** [comment]
I have yet to encounter this certain scenario though. It was an after thought after using the lib.  I'll stick for pinch to zoom for now.

Thanks!
