### ISSUE TITLE
NullpointerException when starting activity

### ISSUE THREAD

**Issue by olavbg** [lawloretienne/ImageGallery#19]
I have followed the description in the Readme, declaring the activity in the manifest, putting the required extras (with ArrayList og string urls) and implementing ImageGalleryAdapter.ImageThumbnailLoader and FullScreenImageGalleryAdapter.FullScreenImageLoader in my calling activity.

But I get a NPE from com.etiennelawlor.imagegallery.library.activities.ImageGalleryActivity.loadImageThumbnail(ImageGalleryActivity.java:101) where the imageThumbnailLoader is NULL. 

Am I doing something wrong? 

StackTrace: https://gist.github.com/olavbg/e19fdc38700d83b3d90e9e1ddf7340d6

- Olav Blaaflat

**Comment by manijak** [comment]
I'm getting the same exception. How do we properly set the loaders, and why is this mandatory all of a sudden?

**Comment by lawloretienne** [comment]
Take a look at MainActivity

https://github.com/lawloretienne/ImageGallery/blob/3e1ed255012a99aa1a245c2aa384eeb216d22370/sample/src/main/java/com/etiennelawlor/imagegallery/activities/MainActivity.java

I am calling

ImageGalleryActivity.setImageThumbnailLoader(this);

and then I am implementing the ImageGalleryAdapter.ImageThumbnailLoader interface in MainActivity.

Do you have all of this setup?

**Comment by olavbg** [comment]
After adding these lines it works again: 

> ImageGalleryActivity.setImageThumbnailLoader(this);
> FullScreenImageGalleryActivity.setFullScreenImageLoader(this);

Should probably point these out in the readme  as well?

Cheers!

**Comment by lawloretienne** [comment]
in the README there is a section titled important note which calls attention to that.

**Comment by antonioreyna** [comment]
i had this same problem but just to mention that the readme jjust says 

```
Important Note

You must now set up image loading by implementing these interfaces ImageGalleryAdapter.ImageThumbnailLoader and FullScreenImageGalleryAdapter.FullScreenImageLoader. See
```

never mention about the methods to set the `this`

Thanks!!
