### ISSUE TITLE
Add Place Holder

### ISSUE THREAD

**Issue by hmz17** [lawloretienne/ImageGallery#2]

**Comment by lawloretienne** [comment]
What exactly do you mean by place holder?

**Comment by norrisboat** [comment]
An image to fill the view whiles the actual image loads

**Comment by hmz17** [comment]
Like when I pass the URL of image. It downloads it through Internet and
then displays it once it gets downloaded. Until then the screen is blank.

What I mean by place holder is, during the time image is being downloaded
the image view will contain some other thing. Like a progress bar or image
showing something else.

Setting a place holder gives us feedback, that image is being downloaded
and mobile is not stalled.

It can be easily done editing the code

Picasso supports both download and error placeholders as optional features.

Picasso.with(context)

.load(url)
.placeholder(R.drawable.user_placeholder)
. error(R.drawable.user_placeholder_error)
. into(imageView);

What exactly do you mean by place holder?

**Comment by lawloretienne** [comment]
Great idea.  I will look into that.

**Comment by lawloretienne** [comment]
![screenshot_20160226-144246](https://cloud.githubusercontent.com/assets/311187/13367418/4f4fa916-dc97-11e5-8913-4937b414e01a.png)

Hey @hmz17 right now I have set the background to grey so it appears that something will be taking its place.  Is that sufficient?

**Comment by hmz17** [comment]
Yes thats fine :smile:
