### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by jdbhai** [lawloretienne/ImageGallery#20]
Error:(30, 29) error: package org.apache.commons.io does not exist

**Comment by lawloretienne** [comment]
When are you getting this error?  I haven't seen this before.  Do any of these links provide more context :
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=error:+package+org.apache.commons.io+does+not+exist

**Comment by lawloretienne** [comment]
Please re-open if this is still an issue.
