### ISSUE TITLE
Margin between images in the same row

### ISSUE THREAD

**Issue by viveknanda** [lawloretienne/ImageGallery#21]
Images in the same row of grid don't seem to have a margin separation between them.. it does exist between the rows.. just not between the columns.

I downloaded your code from github, ran it.. and the UI came out just right.
I copied the same code to a new project (including your images xml file) and images in the same row don't have a margin anymore!

Here's a screenshot: [http://imgur.com/a/U6Bde](url)

**Comment by bmbariah** [comment]
@viveknanda Did you solve this? Kindly share how...

**Comment by lawloretienne** [comment]
I just pushed an update, the latest version 0.1.0 will go live in a couple of hours.  I have removed the ItemDecoration of the RecyclerView.  So there are no longer margins between items in the RecyclerView.
