### ISSUE TITLE
Make it available for fragments

### ISSUE THREAD

**Issue by AyoPrez** [lawloretienne/ImageGallery#3]
Right now the library works fine, but the developer should implement a new activity. Would be great if the library give the option to implement its "magic" in a fragment instead of an Activity.

**Comment by icodeyou** [comment]
I have the same problem, I'd like to use this wonderful gallery in a fragment !
Up !

**Comment by keskin** [comment]
+1 definitely

**Comment by davidfrasch** [comment]
+1 would be great

**Comment by lawloretienne** [comment]
I have added support for just using a Fragment instead of an Activity in the latest update.  It will be live in a couple of hours.
