### ISSUE TITLE
Can I change background color by passing something to the intent?

### ISSUE THREAD

**Issue by shiv19** [lawloretienne/ImageGallery#30]
I want to set the background color to com.etiennelawlor.imagegallery.library.enums.PaletteColorType.LIGHT_VIBRANT

Currently, I am trying

`intent.putExtra("palette_color_type", com.etiennelawlor.imagegallery.library.enums.PaletteColorType.LIGHT_VIBRANT);`

It doesn't work

**Comment by reguez** [comment]
do this  :
 LinearLayout tmp;
    @Override
    public void loadImageThumbnail(ImageView iv, String imageUrl, int dimension) {
     if(tmp==null){
         tmp = (LinearLayout) fragment.getView();
         tmp.setBackgroundColor(Color.RED);
     }
/// rest of the code 
}
