### ISSUE TITLE
add string-value word - "OF"

### ISSUE THREAD

**Issue by klepov** [lawloretienne/ImageGallery#7]
FullScreenImageGalleryActivity.java 
actionBar.setTitle(String.format("%d of %d", (position + 1), totalPages));

for translation in other language.

**Comment by lawloretienne** [comment]
How do you propose i do this?  Do i need to create string resources for multiple languages?  How do I know which languages are important to be covered?

**Comment by lawloretienne** [comment]
Instead of using 1 of 30 i changed it to 1/30 so then I wont need to worry about translating to a language equivalent.

**Comment by klepov** [comment]
i'm override this string in my strings file
