### ISSUE TITLE
 Album Title on the Toolbar

### ISSUE THREAD

**Issue by kprathap23** [lawloretienne/ImageGallery#8]
I have different albums. when i select an album i want to show the title on grid Screen. Is there any way  to set title.

**Comment by lawloretienne** [comment]
Can you please attach a screenshot so I can see what you are talking about?

**Comment by kprathap23** [comment]
![ScreenShot](https://dl.dropboxusercontent.com/u/83669745/images/ImageGallery_Screenshot6.png)

**Comment by lawloretienne** [comment]
Oh thats a good idea.  I will look into that.

**Comment by kprathap23** [comment]
Thanks.

**Comment by lawloretienne** [comment]
This has been fixed in versoin 0.0.14 .
